services:

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: fastapi_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: redis_server
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    container_name: fastapi_app
    restart: always
    ports:
      - "8000:8000"

    depends_on:
      - db
      - redis

    environment:
      DATABASE_URL: postgresql://user:password@db:5432/fastapi_db

      OTEL_SERVICE_NAME: fresh-training-api
      OTEL_EXPORTER_OTLP_ENDPOINT: http://signoz-ingester-1:4317
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc

    networks:
      - default
      - signoz-network

    volumes:
      - .:/app
      - ./keys:/app/keys

volumes:
  postgres_data:
    external: true
    name: task_management_python_project_postgres_data


networks:
  signoz-network:
    external: true