"""initial

Revision ID: 7caa6743aab8
Revises: 
Create Date: 2026-08-09 10:19:13.663835

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7caa6743aab8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('investments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.drop_index(op.f('ix_projects_status'), table_name='projects')
    op.drop_constraint(op.f('uq_transactions_idempotency_key'), 'transactions', type_='unique')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=True)
    op.create_index('idx_transactions_user_created_id', 'transactions', ['user_id', 'created_at', 'id'], unique=False)
    op.create_index(op.f('ix_transactions_wallet_id'), 'transactions', ['wallet_id'], unique=False)
    op.alter_column('wallets', 'user_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.create_check_constraint('cw_wallet_balance_non_negative', 'wallets', 'balance >= 0')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('cw_wallet_balance_non_negative', 'wallets', type_='check')
    op.alter_column('wallets', 'user_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_index(op.f('ix_transactions_wallet_id'), table_name='transactions')
    op.drop_index('idx_transactions_user_created_id', table_name='transactions')
    op.drop_index(op.f('ix_transactions_idempotency_key'), table_name='transactions')
    op.create_index(op.f('ix_transactions_idempotency_key'), 'transactions', ['idempotency_key'], unique=False)
    op.create_unique_constraint(op.f('uq_transactions_idempotency_key'), 'transactions', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_projects_status'), 'projects', ['status'], unique=False)
    op.alter_column('investments', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
